receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}
  prometheus:
    config:
      scrape_configs:
        - job_name: 'fitme'
          static_configs:
            - targets: ['fitme-dev:8001']  # Replace with the actual service name and port

processors:
  batch: {}  # Simplified to only use the batch processor

exporters:
  otlp:
    endpoint: tempo:4317  # Replace 'tempo' with the actual service name if using Jaeger
  prometheus:
    endpoint: "0.0.0.0:9464"  # Expose metrics for Prometheus

service:
  pipelines:
    metrics:
      receivers: [prometheus, otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
