global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'kirk-grpc-service-monitor'

#remote_write:
#  - url: http://localhost:9009/api/v1/push

scrape_configs:
#  - job_name: aggregated-trace-metrics
#    static_configs:
#      - targets: [ 'spm_metrics_source:8889' ]

  - job_name: "otel-collector-prometheus"
    metrics_path: "/metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:9090']
  - job_name: "app-metrics"
    metrics_path: "/metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ['fitme-dev:8001']
  - job_name: 'tempo'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'tempo:3200' ]
#  - job_name: "prometheus"
#    honor_labels: true
#    static_configs:
#      - targets: ["localhost:9090"]
