mode: "dev"
dotenv: ".env/dev"

handlers:
  externalAPI:
    port: "8081"
    certFile: "./.data/server.crt"
    keyFile: "./.data/server.key"
    enableTLS: false
  internalAPI:
    port: "8083"
    certFile: "./.data/server.crt"
    keyFile: "./.data/server.key"
    enableTLS: false
  pprof:
    port: "8082"
    certFile: "./.data/server.crt"
    keyFile: "./.data/server.key"
    enableTLS: false
  prometheus:
    port: "8084"
    certFile: "./.data/server.crt"
    keyFile: "./.data/server.key"
    enableTLS: false

services:
  auth:
    authTokenTTL: 5
    refreshTokenTTL: 20160
    pubKeyFile: "./.data/id_rsa.pub"
    pemKeyFile: "./.data/id_rsa"

repositories:
  postgres:
    port: "5440"
    username: "postgres"
    db: "fit-me-dev"
    SSLMODE: "verify-full"
    MAXCONWAITINGTIME: 10
  redis:
    host: "localhost"
    port: "6388"
    db: 0


#change later
server:
  HTTPPort: "7077"
  GRPCPort: "8000"
  HTTPTimeout: 15s

UpstreamServices:
  Customer: "http://customer-service:8080"
  Auth: "http://auth-service:8080"
  Activity: "http://activity-service:8080"
  Calculator: "http://calculator-service:8080"
  Workout: "http://workout-service:8080"
  Measurement: "http://measurement-service:8080"


