receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4318
processors:
extensions:
  health_check: {}

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
  debug:

connectors:
  spanmetrics:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [spanmetrics, otlp]

    metrics:
      receivers: [spanmetrics]
      processors: []
      exporters: [prometheus]
