# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: grafana-alloy-host:4317
      http:
        endpoint: grafana-alloy-host:4318
processors:
extensions:
  health_check: {}
exporters:
  prometheus:
    endpoint: 0.0.0.0:9090
    namespace: testapp
  debug:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp, debug]

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus, debug]
