global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9091']

  - job_name: "http-fitme-dev"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8001']
