global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'kirk-grpc-service-monitor'

scrape_configs:
  - job_name: aggregated-trace-metrics
    static_configs:
      - targets: [ 'spm_metrics_source:8889' ]

  - job_name: "otel-collector-prometheus"
    metrics_path: "/metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:9090']

  - job_name: "app-metrics"
    metrics_path: "/metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ['fitme-dev:8001']
