global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'kirk-grpc-service-monitor'

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:9090']

  - job_name: "http-fitme-dev"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8001']
