apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      prometheus:
        config:
          scrape_configs:
            - job_name: 'k8s-metrics'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app]
                  action: keep
                  regex: fitme

    processors:
      batch: {}  # Group telemetry data into batches

    exporters:
      prometheus:
        endpoint: "0.0.0.0:9464"  # Expose metrics for Prometheus scraping
      otlphttp/loki:
        endpoint: http://loki.monitoring:3100/loki/api/v1/push
      otlp:
        endpoint: tempo.monitoring.svc.cluster.local:4317  # Send traces to Tempo

    service:
      pipelines:
        metrics:
          receivers: [prometheus, otlp]
          processors: [batch, k8sattributes]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/loki]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
