apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fitme-service-monitor
  namespace: fitmeapp
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: fitme
  namespaceSelector:
    matchNames:
      - fitmeapp
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
