global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'kirk-grpc-service-monitor'

scrape_configs:
  - job_name: "otel-collector"
    metrics_path: "/metrics"
    static_configs:
      - targets: ['otel-collector.fitme-app-dev.svc.cluster.local:9090']

  - job_name: "tempo"
    metrics_path: "/metrics"
    static_configs:
      - targets: ['tempo.fitme-app-dev.svc.cluster.local:3100']
